[unstable]
build-std = ["core", "compiler_builtins"]

[build]
target = "x86_64-req.json"
rustflags = ["-A","dead_code","-A","unused_variables"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
