[package]
name = "your-csnel"
version = "0.1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
csnel = { path="/csnel-src" }
bootloader = { version = ">=0.9.8", features = ["map_physical_memory"]}
